### ISSUE TITLE
Circuit elements

### ISSUE THREAD

**Issue by benoitseron** [benoitseron/BosonSampling.jl#34]
Need to combine both definitions of circuits elements (BS,...), as well as build a proper type hierarchy for them

**Comment by AntoineRestivo** [comment]
What do you mean by a proper type hierarchy? The ones already defined are subtypes of Interferometer. 
Perhaps you think about a new subtype of Interferometer, something like BeamSplitter <: BuildinInterferometer <: Interferometer?

**Comment by benoitseron** [comment]
Sorry I meant more tools, in fact we can also have a type hierarchy with Linear and Gaussian stuff (as we'll do for measurements)

But I don't know if writing the stuff by ourselves is intelligent or if we should simply use https://github.com/qojulia/QuantumOpticsBase.jl

**Comment by benoitseron** [comment]
Btw this too could be a great inspiration for your gaussian stuff. Unsure if their framework is easily convertible to what you'd want to do.
